"""rm University state and address

Revision ID: 0725fa2e98a5
Revises: 71ddc9603137
Create Date: 2018-05-07 19:49:55.955635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0725fa2e98a5'
down_revision = '71ddc9603137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_university_state', table_name='university')
    op.drop_column('university', 'state')
    op.drop_column('university', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('address', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('university', sa.Column('state', mysql.VARCHAR(length=32), nullable=True))
    op.create_index('ix_university_state', 'university', ['state'], unique=False)
    # ### end Alembic commands ###
