"""update university table and add rank table

Revision ID: 2873c7b19171
Revises: 
Create Date: 2018-05-07 16:22:40.849612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2873c7b19171'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('university',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_university_name'), 'university', ['name'], unique=True)
    op.create_index(op.f('ix_university_state'), 'university', ['state'], unique=False)
    op.create_table('rank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uni_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('quality_of_education', sa.Integer(), nullable=True),
    sa.Column('alumni_employment', sa.Integer(), nullable=True),
    sa.Column('quality_of_faculty', sa.Integer(), nullable=True),
    sa.Column('publications', sa.Integer(), nullable=True),
    sa.Column('influence', sa.Integer(), nullable=True),
    sa.Column('citations', sa.Integer(), nullable=True),
    sa.Column('broad_impact', sa.Integer(), nullable=True),
    sa.Column('patents', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uni_id'], ['university.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rank_rank'), 'rank', ['rank'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rank_rank'), table_name='rank')
    op.drop_table('rank')
    op.drop_index(op.f('ix_university_state'), table_name='university')
    op.drop_index(op.f('ix_university_name'), table_name='university')
    op.drop_table('university')
    # ### end Alembic commands ###
