"""Research income and HDR completions table

Revision ID: 71ddc9603137
Revises: 2873c7b19171
Create Date: 2018-05-07 16:56:46.476375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71ddc9603137'
down_revision = '2873c7b19171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('HDR_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uni_id', sa.Integer(), nullable=True),
    sa.Column('research_master_hc_non_indigenous', sa.String(length=32), nullable=True),
    sa.Column('research_master_lc_non_indigenous', sa.String(length=32), nullable=True),
    sa.Column('research_doctorate_hc_non_indigenous', sa.String(length=32), nullable=True),
    sa.Column('research_doctorate_lc_non_indigenous', sa.String(length=32), nullable=True),
    sa.Column('total_non_indigenous_unweighted', sa.String(length=32), nullable=True),
    sa.Column('research_master_hc_indigenous', sa.String(length=32), nullable=True),
    sa.Column('research_master_lc_indigenous', sa.String(length=32), nullable=True),
    sa.Column('research_doctorate_hc_indigenous', sa.String(length=32), nullable=True),
    sa.Column('research_doctorate_lc_indigenous', sa.String(length=32), nullable=True),
    sa.Column('total_indigenou_unweighted', sa.String(length=32), nullable=True),
    sa.Column('grand_total_non_indigenous_and_indigenous_unweighted', sa.Integer(), nullable=True),
    sa.Column('grand_total_non_indigenous_and_indigenous_weighted', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uni_id'], ['university.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uni_id', sa.Integer(), nullable=True),
    sa.Column('applications', sa.Integer(), nullable=True),
    sa.Column('offers', sa.Integer(), nullable=True),
    sa.Column('offer_rates', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uni_id'], ['university.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uni_id', sa.Integer(), nullable=True),
    sa.Column('australian_competitive_grants', sa.Text(), nullable=True),
    sa.Column('other_public_sector_research_funding', sa.Text(), nullable=True),
    sa.Column('industry_and_other_funding', sa.Text(), nullable=True),
    sa.Column('cooperative_research_center_funding', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uni_id'], ['university.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('research_income')
    op.drop_table('enrollments')
    op.drop_table('HDR_completions')
    # ### end Alembic commands ###
