"""init

Revision ID: fea017106967
Revises: 
Create Date: 2018-05-23 17:21:44.949802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fea017106967'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=8), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universities_name'), 'universities', ['name'], unique=True)
    op.create_table('HDR_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uni_id', sa.Integer(), nullable=True),
    sa.Column('research_master_hc_non_indigenous', sa.String(length=32), nullable=True),
    sa.Column('research_master_lc_non_indigenous', sa.String(length=32), nullable=True),
    sa.Column('research_doctorate_hc_non_indigenous', sa.String(length=32), nullable=True),
    sa.Column('research_doctorate_lc_non_indigenous', sa.String(length=32), nullable=True),
    sa.Column('total_non_indigenous_unweighted', sa.String(length=32), nullable=True),
    sa.Column('research_master_hc_indigenous', sa.String(length=32), nullable=True),
    sa.Column('research_master_lc_indigenous', sa.String(length=32), nullable=True),
    sa.Column('research_doctorate_hc_indigenous', sa.String(length=32), nullable=True),
    sa.Column('research_doctorate_lc_indigenous', sa.String(length=32), nullable=True),
    sa.Column('total_indigenou_unweighted', sa.String(length=32), nullable=True),
    sa.Column('grand_total_non_indigenous_and_indigenous_unweighted', sa.String(length=32), nullable=True),
    sa.Column('grand_total_non_indigenous_and_indigenous_weighted', sa.String(length=32), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uni_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uni_id', sa.Integer(), nullable=True),
    sa.Column('applications', sa.Integer(), nullable=True),
    sa.Column('offers', sa.Integer(), nullable=True),
    sa.Column('offer_rates', sa.Float(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uni_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geo_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uni_id', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uni_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ranks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uni_id', sa.Integer(), nullable=True),
    sa.Column('world_rank', sa.Integer(), nullable=True),
    sa.Column('national_rank', sa.Integer(), nullable=True),
    sa.Column('quality_of_education', sa.Integer(), nullable=True),
    sa.Column('alumni_employment', sa.Integer(), nullable=True),
    sa.Column('quality_of_faculty', sa.Integer(), nullable=True),
    sa.Column('publications', sa.Integer(), nullable=True),
    sa.Column('influence', sa.Integer(), nullable=True),
    sa.Column('citations', sa.Integer(), nullable=True),
    sa.Column('broad_impact', sa.Integer(), nullable=True),
    sa.Column('patents', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uni_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ranks_national_rank'), 'ranks', ['national_rank'], unique=False)
    op.create_index(op.f('ix_ranks_world_rank'), 'ranks', ['world_rank'], unique=False)
    op.create_table('research_incomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uni_id', sa.Integer(), nullable=True),
    sa.Column('australian_competitive_grants', sa.Text(), nullable=True),
    sa.Column('other_public_sector_research_funding', sa.Text(), nullable=True),
    sa.Column('industry_and_other_funding', sa.Text(), nullable=True),
    sa.Column('cooperative_research_center_funding', sa.Text(), nullable=True),
    sa.Column('grand_total', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uni_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('research_incomes')
    op.drop_index(op.f('ix_ranks_world_rank'), table_name='ranks')
    op.drop_index(op.f('ix_ranks_national_rank'), table_name='ranks')
    op.drop_table('ranks')
    op.drop_table('geo_info')
    op.drop_table('enrollments')
    op.drop_table('HDR_completions')
    op.drop_index(op.f('ix_universities_name'), table_name='universities')
    op.drop_table('universities')
    # ### end Alembic commands ###
