"""add national_rank and rename rank to word_rank

Revision ID: ffa954cfb74d
Revises: 0725fa2e98a5
Create Date: 2018-05-07 22:03:12.257199

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ffa954cfb74d'
down_revision = '0725fa2e98a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rank', sa.Column('national_rank', sa.Integer(), nullable=True))
    op.add_column('rank', sa.Column('word_rank', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_rank_national_rank'), 'rank', ['national_rank'], unique=False)
    op.create_index(op.f('ix_rank_word_rank'), 'rank', ['word_rank'], unique=False)
    op.drop_index('ix_rank_rank', table_name='rank')
    op.drop_column('rank', 'rank')
    op.add_column('research_income', sa.Column('grand_total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_income', 'grand_total')
    op.add_column('rank', sa.Column('rank', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('ix_rank_rank', 'rank', ['rank'], unique=True)
    op.drop_index(op.f('ix_rank_word_rank'), table_name='rank')
    op.drop_index(op.f('ix_rank_national_rank'), table_name='rank')
    op.drop_column('rank', 'word_rank')
    op.drop_column('rank', 'national_rank')
    # ### end Alembic commands ###
